pytition/Pytition

- pytition/petition/views.py
Ajout de l'email de la personne dans le message prévenant qu'elle va en recevoir un pour valider sa signature.
C'est pour permettre de facilement vérifier si on a entré la bonne adresse sans avoir à ressigner la pétition dans le doute, tant qu'on a pas fermé la page de la pétition en tout cas.
Je suis pas sûr que ce que j'ai fait marche, je dirai que oui mais je suis pas sûr, du coup hésites pas à corriger ^^
> Ajout de l'email de la personne dans le message

- Dockerfile
- Jenkinsfile
- dev/dev_setup.sh
- requirements.txt
- requirements_dev.txt
split the requirements in 2 files.
This makes it possible to not install dev dependencies in production (like coverage)
The dev requirements are still installed in the docker since it seems the dockers are only used for dev purposes
fixes #72
> split requirements.txt

- README.md
Before deploying, the static files need to be copied to their served directory.
> Add missing collectstatic call in README

- dev/initialize.sh
* Show available options and default option for answering prepopulation prompt in `dev/initialize.sh`.
* Doesn't change script behaviour.
* Tested with `docker-compose` on Mac OS.
> feat - Add options display for prepopulate script prompt

- pytition/locale/fr_FR/LC_MESSAGES/django.po
It seems that double escaping of single quotes is not useful, and the displayed text did contain an escaped back slash.
* Removed all occurrences in `fr_FR:django.po`.
* [ ] Translation compilation updated
* Tested with `docker-compose` on Mac OS.
* `django-admin compilemessages` ran successfully
> fix - Remove double escaped single quotes from translations

- pytition/petition/templates/registration/login.html
Hello,
A small pull request to concern the registration form. On mobile, fields are too small. See pictures :
intial screen for existant and others pictures for differents sizes after modification.
A great tool Pytition.
Thanks.
----
*on mobile screen after modification*
*on tablet screen after modification*
*on large screen after modification*
*Inittial*
> On small screen form is too small

- pytition/petition/templates/petition/new_petition_step3.html
Hello there!
Simple change to remove the clickable image at the end of petition creation (fixes #197)
I deleted the `a` tag altogether because the class `sb-preview-img` did not seem to have any effect.
> Fix #197 clickable img in petition creation 

- pytition/petition/templates/petition/signature_data.html
Fix #166 
Decided to use `h4` to try to make it fit in one line even if the petition title is relatively long
> Fix #166 add petition title in "show signatories" page

- pytition/petition/templates/layouts/nav.html
- pytition/petition/templates/layouts/nav_dashboard.html
- pytition/pytition/settings/base.py
Fixes #194
I needed to make a couple of changes in the base settings file because Occitan is not officially supported by Django.
WIP as the following points need to be discussed:
**1) the UI rendering**
I made it look this way for now, but happy to change if you have a suggestion:
**2) the list of languages**
Currently it gets all the languages even when the translation is incomplete / missing, because of this line `LANGUAGES = global_settings.LANGUAGES`. I would advise to have a list of languages set in the base settings file
> Fix #194 Add language selection form

- Dockerfile
Minor tweaks to follow [Dockerfile best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) a bit closer.
- Pin version of the python image to prevent failures due to unanticipated changes
- Only one layer for the installation of packages (gettext)
- Apt cache cleaned up to reduce the image size
> Couple of best practices for Dockerfile

- dev/generate_docker_config.sh
- doc/installation.rst
- docker-compose.yml
Fixes https://github.com/pytition/Pytition/issues/231
Adds Maildev in docker-compose to allow people to play with features requiring SMTP server up
Notes:
* I used the default ports (25 for smtp, 8080 for web interface), that can easily be changed if needed.
* I used the script generate_docker_config.sh for the settings, I'll let you confirm whether this was a good idea :)
* I did not write any documentation about this
> Add Maildev as Fake SMTP for dev

- pytition/petition/management/commands/update.py
This update command does:
- git checkout master && git pull
- git checkout to the last version
- lauch pip3 install --upgrade -r requirements.txt
- manage.py migrate
- manage.py collectstatic
- manage.py compilemessages
**TODO:**
> feat: add update command to manage.py

- pytition/petition/forms.py
- pytition/petition/templates/registration/register.html
- pytition/petition/tests/tests_RegisterView.py
- pytition/petition/urls.py
- pytition/petition/views.py
This allows very basic captcha functionality to user registration.
Now, a simple addition is needed in order to register.
A fake, hidden, email confirmation field is also checked. If the fake email field is filled-up, then registration is canceled.
> Add simple captcha for registering form

- pytition/petition/templates/petition/index.html
Very minor update: only show the "Create a petition" button on home page if logged in
I used the occasion to correct the indentation on the lines above to be more consistent with the rest of the code.
Fixes https://github.com/pytition/Pytition/issues/241
> Only show "Create a petition" if logged in

- pytition/petition/templates/petition/generic_petition_list.html
- pytition/petition/templates/petition/index.html
- pytition/petition/templates/petition/org_profile.html
- pytition/petition/templates/petition/user_profile.html
- pytition/petition/views.py
Fixes #195
- This pull request adds chronological sorting to the Home page, User profile page, organization page.
- "creation_date" is used for sorting
- I initially planned to use drop-down for sorting. But I chose "segmented button" because I think it looks nicer on UI and the code will be simpler.
I am happy to fix or refactor if there are any problems with code, UI, etc.
**Orgnization Profile Page**
**User Profile Page**
**Home Page**
> Fixes #195 add chronological sorting to home page, user/org profile page

- pytition/petition/templates/503.html
- pytition/pytition/settings/base.py
- pytition/pytition/urls.py
- requirements.txt
With django-maintenance-mode, the site can be stopped before an upgrade or a database migration. The goal is to maintain the coherence of the database during the upgrade process.
> feat: add django-maintenance-mode requirement

- pytition/petition/management/commands/update.py
The purpose of the update command is to be used with cronjob.
Currently the git commands inside are two verbose to be useful
> feat: make update commande more quiet

- pytition/petition/templates/registration/login.html
When register option is false, the password reset link desepear. This fix it.
> fix: always show password reset link on login template

- pytition/petition/templates/petition/org_member_list.html
When first and last name are empty, nothing is print in the organisation owner/member part
This fixes it.
> fix: print membre.username if membre.get_full_name is empty

- Dockerfile
- Jenkinsfile
- README.md
- dev/INSTALL.md
- doc/configuration.rst
- doc/installation.rst
- doc/multi-domain-install.rst
- pytition/locale/fr_FR/LC_MESSAGES/django.po
- pytition/petition/admin.py
- pytition/petition/forms.py
- pytition/petition/helpers.py
- pytition/petition/models.py
- pytition/petition/templates/petition/bs4_form.html
- pytition/petition/templates/petition/edit_petition.html
- pytition/petition/tests/tests_EditPetitionView.py
- pytition/petition/urls.py
- pytition/petition/views.py
- pytition/pytition/settings/base.py
- pytition/pytition/settings/config_example.py
- pytition/pytition/urls.py
- requirements.txt
Let's update Django to latest LTS : 4.2
> Update to Django 4.2

- Dockerfile
- doc/installation.rst
I don’t know pdm but it seems it needs the correct venv path in `PDM_PYTHON` env var, or in `.pdm-python` file which is apparently generated by `pdm use -f /venv/.venv`. Also, subsequent python commands seems to need to be run with `pdm run …`
To be confirmed but for me, it fix #328
> pdm docker: fix venv path

- pytition/petition/templates/layouts/nav-useractions.html
- pytition/petition/templates/petition/account_settings.html
- pytition/petition/templates/petition/user_org_list.html
- pytition/petition/views.py
- pytition/pytition/settings/base.py
> Issue 326 : Restrict organization creation : use Django permissions
