pytition/petition/views.py
Teste et retourne un retourne un message d'erreur.
Le mieux à terme serait aussi de tester le contenu pour voir si c'est composé de lettre de l'alphabet (et pas juste de point et d'espace ou du genre)
=> Test if firstname and lastname string are empty

dev/dev_setup.sh
See https://github.com/fallen/Pytition/issues/64
=> Quick fix for the mixed answer when my.cnf exists

pytition/petition/templates/petition/petition_detail.html, pytition/petition/tests/tests_PetitionDetailView.py, pytition/petition/views.py
This fixes #94
It removes an hardocded url "petition.antipub.org" and uses the host for metadata
=> remove hardcoded petition.antipub.org

pytition/petition/static/css/petition.css, pytition/petition/templates/layouts/nav.html, pytition/petition/templates/petition/base.html
Moved navbar in its ownfile to make base.html clearer and make it prettier. 💅
=> extract and clean navbar

pytition/petition/tests/tests_PetitionDetailView.py, pytition/petition/views.py
=> Fix integration tests

pytition/petition/models.py, pytition/petition/views.py
There is an encoding bug in the salt storage and in the creation of hashed IP addresses. This PR fixes it.
=> Fixes encoding bug in salts and hash of IP addresses

pytition/cli_pytition.py
This makes it possible to easily mock some signature via the cli
=> Add generate_signatures to cli

.gitignore, pytition/petition/helpers.py, pytition/petition/templates/layouts/nav.html, pytition/petition/templates/petition/index.html, pytition/petition/templates/registration/login.html, pytition/petition/templates/registration/password_reset_done.html, pytition/petition/templates/registration/password_reset_form.html, pytition/petition/tests/tests_AccountSettingsView.py, pytition/petition/tests/tests_LeaveOrg.py, pytition/petition/tests/tests_PetitionCreationWizard.py, pytition/petition/views.py
Several commits in this PR, one to move view helpers in `helpers.py`, and two to improve login and password reset views.
The first one may break things because code has been moved here and there
=> Improve view and controllers

pytition/petition/models.py, pytition/petition/tests/tests_Petition.py
=> Fixes bug in Petition.url

pytition/petition/static/css/dashboard.css, pytition/petition/templates/layouts/base.html, pytition/petition/templates/layouts/dashboard_layout.html, pytition/petition/templates/layouts/footer.html, pytition/petition/templates/layouts/layout.html, pytition/petition/templates/layouts/nav_dashboard.html, pytition/petition/templates/petition/account_settings.html, pytition/petition/templates/petition/all_petitions.html, pytition/petition/templates/petition/base.html, pytition/petition/templates/petition/dashboard_alert.html, pytition/petition/templates/petition/index.html, pytition/petition/templates/petition/new_petition_step1.html, pytition/petition/templates/petition/new_petition_step3.html, pytition/petition/templates/petition/org_base.html, pytition/petition/templates/petition/org_invite_user.html, pytition/petition/templates/petition/org_member_list.html, pytition/petition/templates/petition/petition_detail.html, pytition/petition/templates/petition/petition_list.html, pytition/petition/templates/petition/profile.html, pytition/petition/templates/petition/search.html, pytition/petition/templates/petition/template_list.html, pytition/petition/templates/petition/user_base.html, pytition/petition/templates/petition/user_dashboard.html, pytition/petition/templates/petition/user_invitations.html, pytition/petition/templates/petition/user_org_list.html, pytition/petition/templates/registration/login.html, pytition/petition/templates/registration/register.html
Extract layouts and fix containers on public pages.
Depends on #122
=> Refactor layouts

pytition/petition/static/css/petition.css, pytition/petition/templates/petition/petition_detail.html, pytition/petition/views.py
=> Improve petition

pytition/petition/templates/layouts/nav_dashboard.html, pytition/petition/templates/petition/org_profile.html, pytition/petition/templates/petition/search.html, pytition/petition/templates/petition/user_profile.html, pytition/petition/templates/registration/login.html, pytition/petition/views.py
Improve :
* Org and user profile page
* Navbar
* search results
=> Minor modifications of the views

pytition/petition/templates/petition/account_settings.html
=> Fixes button bug of #138

pytition/petition/templates/layouts/nav_dashboard.html
=> Fixes search bug dashboard nav

pytition/petition/templates/layouts/base.html, pytition/petition/templates/registration/register.html
- Fix blank space in register form by modify justify setting for app
- Add a block to base template to set justify mode for app
- Remove unused html code in register template
- Improve display for mobile
Related to #145
=> Fix register page

pytition/petition/views.py
Fix bug #119 
I am wondering if it could be better to use a helper function to find user instead of duplicate the code.
=> Fix user missing in detail view context

pytition/petition/templates/petition/user_profile.html
=> Remove stray div closing tag on user_profile

pytition/locale/fr_FR/LC_MESSAGES/django.po
=> Fix #188 typo in dashboard

dev/dev_setup.sh
I'm not 100% sure but it looks like this file have moved
=> Fix the dev script

pytition/petition/views.py
=> user dashboard: Bring back petitions count

dev/prepopulate.sh, pytition/petition/management/commands/gen_orga.py, pytition/petition/management/commands/gen_pet.py, pytition/petition/management/commands/gen_sig.py, pytition/petition/management/commands/gen_user.py, pytition/petition/management/commands/join_org.py, pytition/petition/tests/test_Commands.py
- Closes #220 
- The only difference from the original cli is that signatures are confirmed when they are created
=> Create custom Django commands - Issue 220

pytition/petition/templates/petition/all_petitions.html, pytition/petition/templates/petition/generic_petition_list.html, pytition/petition/templates/petition/index.html, pytition/petition/tests/tests_AccountSettingsView.py, pytition/petition/tests/tests_AllPetitions.py, pytition/petition/tests/tests_Indexviews.py, pytition/petition/urls.py, pytition/petition/views.py, pytition/pytition/settings/base.py
Fixes #240 
**Notes:**
* I added a simple pagination, without "first" and "last" buttons, this could be added later on
* I made it a way to avoid making changes which require new translations, but that's up to you
* I made the choice to add the pagination code into `generic_petition_list.html` rather than `index.html`, but it could work on either
=> Add pagination for petitions (#240)

pytition/petition/forms.py, pytition/petition/helpers.py, pytition/petition/templates/registration/confirmation_email.html, pytition/petition/tests/tests_RegisterView.py, pytition/petition/views.py, pytition/pytition/settings/base.py
=> Send a welcome mail on account creation
